export const CANT_FIND_LIB_BY_NAME = 'CANT_FIND_LIB_BY_NAME';
export const CANT_GET_LIB_SOLDERBALL = 'CANT_GET_LIB_SOLDERBALL';
export const CANT_FIND_LIB_VERSION = 'CANT_FIND_LIB_VERSION';
export const CANT_PARSE_LIBRARY_REQUEST = 'CANT_PARSE_LIBRARY_REQUEST';
export const INVALID_SOLDERBALL = 'INVALID_SOLDERBALL';
export const SERVICE_UNAVAILABLE = 'SERVICE_UNAVAILABLE';
export const CANT_GET_SWAGGER = 'CANT_GET_SWAGGER';
