export const THEME_KEYS = [
  'chromeBg',
  'chromeTitleBg',
  'chromeOutlines',
  'chromeLightBg',
  'text',
  'menubarBg',
  'menubarText',
  'menubarActiveBg',
  'menubarActiveText',
  'menubarHoverBg',
  'tabBg',
  'tabItemBg',
  'tabText',
  'sidebarBg',
  'sidebarHoverBg',
  'sidebarSelectedBg',
  'sidebarSelectedHoverBg',
  'sidebarText',
  'sidebarSubtitle',
  'canvasBg',
  'canvasGridlines',
  'canvasFace',
  'canvasFaceLight',
  'canvasFaceText',
  'nodeFill',
  'nodeLabel',
  'nodeOutlines',
  'pinBg',
  'pinLabel',
  'commentText',
  'highlight',
  'inputBg',
  'inputText',
  'inputBorder',
  'darkButtonBg',
  'darkButtonHoverBg',
  'darkButtonText',
  'lightButtonBg',
  'lightButtonText',
  'selected',
  'error',
  'errorText',
];

const navy = {
  chromeBg: '#2c3e50',
  chromeTitleBg: '#283748',
  chromeOutlines: '#1e2a38',
  chromeLightBg: '#c7cfd6',
  text: '#c7cfd6',
  menubarBg: '#24333f',
  menubarText: '#c7cfd6',
  menubarActiveBg: '#1e2a38',
  menubarActiveText: '#ff6b6b',
  menubarHoverBg: '#3d5468',
  tabBg: '#1e2a38',
  tabItemBg: '#283748',
  tabText: '#c7cfd6',
  sidebarBg: '#2c3e50',
  sidebarHoverBg: '#4c5f72',
  sidebarSelectedBg: '#3d5468',
  sidebarSelectedHoverBg: '#4a6883',
  sidebarText: '#c7cfd6',
  sidebarSubtitle: '#8a97a3',
  canvasBg: '#24333f',
  canvasGridlines: '#34495e',
  canvasFace: '#646464',
  canvasFaceLight: '#eef1f3',
  canvasFaceText: '#a7a7a7',
  nodeFill: '#22303f',
  nodeLabel: '#c7cfd6',
  nodeOutlines: '#a9b4bd',
  pinBg: '#22303f',
  pinLabel: '#a9b4bd',
  commentText: '#d0ccc0',
  highlight: '#eeeeee',
  inputBg: '#2f3f4f',
  inputText: '#c7cfd6',
  inputBorder: '#4c5f72',
  darkButtonBg: '#34495e',
  darkButtonHoverBg: '#3d5468',
  darkButtonText: '#c7cfd6',
  lightButtonBg: '#3d5468',
  lightButtonText: '#eef1f3',
  selected: '#ff6b6b',
  error: '#c33d3d',
  errorText: '#fd6161',
};

const light = {
  chromeBg: '#ffffff',
  chromeTitleBg: '#f8fafc',
  chromeOutlines: '#e2e8f0',
  chromeLightBg: '#f1f5f9',
  text: '#1f2933',
  menubarBg: '#ffffff',
  menubarText: '#334155',
  menubarActiveBg: '#fff1f2',
  menubarActiveText: '#ff6b6b',
  menubarHoverBg: '#f1f5f9',
  tabBg: '#eef1f5',
  tabItemBg: '#ffffff',
  tabText: '#64748b',
  sidebarBg: '#f8fafc',
  sidebarHoverBg: '#eef1f5',
  sidebarSelectedBg: '#ffe4e6',
  sidebarSelectedHoverBg: '#ffd3d6',
  sidebarText: '#334155',
  sidebarSubtitle: '#94a3b8',
  canvasBg: '#ffffff',
  canvasGridlines: '#eef1f5',
  canvasFace: '#a8b3bf',
  canvasFaceLight: '#f1f5f9',
  canvasFaceText: '#64748b',
  nodeFill: '#ffffff',
  nodeLabel: '#1f2933',
  nodeOutlines: '#cbd5e1',
  pinBg: '#f1f5f9',
  pinLabel: '#64748b',
  commentText: '#64748b',
  highlight: '#f1f5f9',
  inputBg: '#ffffff',
  inputText: '#1f2933',
  inputBorder: '#cbd5e1',
  darkButtonBg: '#1e293b',
  darkButtonHoverBg: '#334155',
  darkButtonText: '#ffffff',
  lightButtonBg: '#f1f5f9',
  lightButtonText: '#1f2933',
  selected: '#ff6b6b',
  error: '#dc2626',
  errorText: '#b91c1c',
};

const nordic = {
  chromeBg: '#1b2836',
  chromeTitleBg: '#101720',
  chromeOutlines: '#101720',
  chromeLightBg: '#c7cfd6',
  text: '#c7cfd6',
  menubarBg: '#16222e',
  menubarText: '#c7cfd6',
  menubarActiveBg: '#101720',
  menubarActiveText: '#ff6b6b',
  menubarHoverBg: '#22384a',
  tabBg: '#101720',
  tabItemBg: '#16222e',
  tabText: '#c7cfd6',
  sidebarBg: '#16222e',
  sidebarHoverBg: '#22384a',
  sidebarSelectedBg: '#22384a',
  sidebarSelectedHoverBg: '#2c4257',
  sidebarText: '#c7cfd6',
  sidebarSubtitle: '#7b8db5',
  canvasBg: '#16222e',
  canvasGridlines: '#22384a',
  canvasFace: '#5f7084',
  canvasFaceLight: '#d8dee3',
  canvasFaceText: '#7b8db5',
  nodeFill: '#1b2a39',
  nodeLabel: '#d8dee3',
  nodeOutlines: '#7b8db5',
  pinBg: '#1b2a39',
  pinLabel: '#7b8db5',
  commentText: '#c7cfd6',
  highlight: '#eef1f3',
  inputBg: '#1b2836',
  inputText: '#c7cfd6',
  inputBorder: '#2c4257',
  darkButtonBg: '#22384a',
  darkButtonHoverBg: '#2c4257',
  darkButtonText: '#d8dee3',
  lightButtonBg: '#2c4257',
  lightButtonText: '#eef1f3',
  selected: '#ff6b6b',
  error: '#c33d3d',
  errorText: '#fd6161',
};

export const INITIAL_STATE = {
  currentTheme: 'light',
  themes: {
    navy: {
      name: 'Navy',
      colors: navy,
    },
    light: {
      name: 'Light',
      colors: light,
    },
    nordic: {
      name: 'Nordic',
      colors: nordic,
    },
  },
};
