export const MANAGE_LOCAL_SIMULATION_REQUEST =
  'MANAGE_LOCAL_SIMULATION_REQUEST';
export const MANAGE_LOCAL_SIMULATION_CLOSE = 'MANAGE_LOCAL_SIMULATION_CLOSE';

export const WELCOME_POPUP_CLOSE = 'WELCOME_POPUP_CLOSE';
export const FIRST_LAUNCH_DETECTED = 'FIRST_LAUNCH_DETECTED';
